# -*- coding: utf-8 -*-
"""project004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yG7KnL8f6Nq8QtLGYjSPJNYH_4sT2368

#**Gettin to know : if ,else if ,if else ,elif**
"""

#if
a = int(input('Enter a:'))
b = int(input('Enter b:'))

if a>b : 
  print(a)
print(b)

if True :
  print('gol mamad')
print('gholam')

"""if else"""

#1
x = int(input('Enter x:'))
if x%2 == 0 :
  print('even')
else :
  print('odd')
print('================')

#2
y = int(input('Enter y:'))
if x>y :
  print('x is bigger')
else :
  print('y is bigger')
print('================') 

"""conditional expression"""
#1_1
print('even' if x%2 == 0 else 'odd')
print('================')

#2-2
print('x is bigger' if x > y else 'y isbigger')

#3
s = ['a' , 'e' , 'o' , 'i' , 'u']
print('yes' if('o' in s) else 'no')

""" nested if """
today = 'holidey'
money = 2500 

if today == 'holiday' :
  if money >= 2000 :
    print('go shopping')
  else :
    print('watching TV')
else :
  print('normal working day')

""" else if """
grade = int(input('Enter grade:'))

if grade >= 90 and grade <= 100 :
  print('A')
else :
  if grade >= 80 and grade < 90 :
    print('B')
  else :
    if grade >= 70 and grade < 80 :
      print('C')
    else :
      if grade >= 0 and grade < 70 :
        print('d')
      else :
        print('invalid grade :(') 

print('================================')

""" elif """
grade = int(input('Enter grade:'))

if grade >= 90  and grade <= 100 :
  print('A')
elif grade >= 80 and grade < 90 :
  print('B')
elif grade >= 70 and grade < 80 :
  print('C')
elif grade >= 0 and grade < 70 :
  print('D')
else :
  print('invalid number')

""" bmi Example """
w = 85
h = 1.85
bmi = w / (h*h)

print(bmi)

if bmi < 16 :
  print('very skinny')
elif bmi >= 16 and bmi < 18.5 :
  print('slim')
elif bmi >= 18.5 and bmi < 25 :
  print('normal')
elif bmi >= 25 and bmi < 35 :
  print('fat')
elif bmi >= 35 and bmi < 40 :
  print('class 2 fat')
else :
  print('class 3 fat')
