# -*- coding: utf-8 -*-
"""project007.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ZRX5Q3bfdxKexmSfzQHKlGr6yhMy_bF

# list :)
"""

a = [1 , 2 , 3 , 4]
print(type(a))
print(a)

#index
print(a.index(3))      #2
print(a[2])            #3

a[3] = 3
print(a)
print(a.count(3))

a = [1 , 2]
b = [2 , 1]
print(a == b)

a = 'sara'
# a[2] = 3      ERROR

print('############################')

a = [1 , 2 , 3 , 4]
for i in a:
  print(i , end = ' ')
print()

print('############################')

a = [1 , 2 , 3 , 4]
for i in range(4):
  print(a[i] , end = ' ')

print('\n############################')

a = [3 , 4 , 'ali' , 3.53 , True]
print(a)

#slice
a = [1 , 4 , 4 , 23 , 55 , 23 , 14 , 23]
print(a[:])
print(a[0 : 3])
print(a[3 : 8])
print(a[6 : 3])
print(a[ :: -1])
#step slice
print('\n############################\n')
print(a[3 : 9 : 2])
print(a[: 7 : 3])
print(a[4 :: 1])
print(a[:: 2])

#concat
a = [1 , 2 , 3]
b = a * 2
print(b)

a = [1 , 2 , 3]
b = [4 , 5]
c = a + b
print(c)

print('\n############################\n')

#list in the list
a = [1 , 2 , 3 ,4]
print(3 in a)
print(5 not in a)

a = [1 , 2 , [3 , 4] , 5]
print(a)
print(a[2])
print(a[2][0])

# min max
a = [2 , 12 , 13 , 35 , 30 , 1]
m = a[0]
for i in a:
  if i > m:
    m = i
print(f'max = {m}')

m = a[0]
for i in a:
  if i < m:
    m = i
print('min = {:d}'.format(m))

# list function

#insert and remove
a = [1 , 2 , 3 , 4 , 4 , 5]
print('count {:d}'.format(a.count(4)))
a.insert(4 , 5)
a.insert(5 , 6)
print(a)
a.remove(4)
a.remove(4)
a.remove(5)
a.remove(5)
print(a)
a.insert(3 , 4)
a.insert(4 , 5)
print(a)

print('\n############################\n')

#pop
a = [1 , 2 , 3 , 4 , 5]
x = a.pop()
print(a)
print('pop = {:d}'.format(x))
print('len = {:d}'.format(len(a)))
x = a.pop()
print(a)
print('pop = {:d}'.format(x))
print('len = {:d}'.format(len(a)))

print('\n############################\n')

#delet
a = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8]
del a[1]
print(a)
del a[1 : 5]
print(a)

print('\n############################\n')

#reverse 
a = [1 , 2 , 3 , 4]
print(a)
a.reverse()
print(a)
a.reverse()
print(a)
print(a[:: -1])

print('\n############################\n')

#sort
a = [2 , 10 , 3 , 3 , 6 , 5 , 12 , 11]
a.sort()
print(a)
a.reverse()
print(a)

print('\n############################\n')

#extend
a = [1 , 2 , 3]
b = [4 , 5]
a.extend(b)
print(a)
print('len = {:d}'.format(len(a)))
print(b)
print(f'len = {len(b)}')

print()

a = [1 , 2 , 3]
b = [4 , 5]
b.extend(a)
print(a)
print('len = {:d}'.format(len(a)))
print(b)
print(f'len = {len(b)}')

print('\n############################\n')

#append
a = [1 , 2 , 3]
b = [4 , 5]
a.append(b)
print(a)
print(f'len = {len(a)}')

print()

a = [1 , 2 ,3]
b = [4 , 5]
b.append(a)
print(b)
print(f'len = {len(b)}')

print('\n############################\n')

#clear
a = [1 , 2 , 3 , 4 , 5]
print(f'befor clear : {a}')
a.clear()
print(f'after clear : {a}')

print('\n############################\n')

#copy
a = [1 , 2 , 3 , 4]
b = a.copy()
print(f'a = {a}')
print(f'b = {b}')

#Ex1
a = []
for i in range(4):
  a.append(i)
print(a)

a = []
for i in range(2 , 6):
  a.append(i)
print(a)

a = [i for i in range(4)]
print(a)

a = [i for i in range(2 , 6)]
print(a)

a = [i*i for i in range(3 , 6)]         # a = [9 , 16 , 25]
print(f'a without append : {a}')

a = []
for i in range(3 , 6):
  a.append(i*i)
print(f'a with append : {a}')

print('\n############################\n')

#Ex2
a = [-1 , 3 , 12 , -21 , -2 , -8]
print(a)
length = len(a)
for i in range(0,length):
  a[i] = abs(a[i])
print(a)
a.sort()
print(a)
a.reverse()
print(a)

print()

a = [3 , -3 , -6 , 5 , -43 , -534]
print(a)
b = [abs(i) for i in a]
print(b)

print('\n############################\n')

#Ex2
import math
a = [round(math.pi , i) for i in range(1 , 6)]
print(a)

print('\n############################\n')

#Ex3
a = ['$ali' , 'sara&']
a = [i.strip('$') for i in a]
print(a)

print('\n############################\n')

#Ex4
a = [18 , 4 , 9 , 12 , 13 , 20 , 2]
b = [i for i in a if i < 10]
print(f'fail = {b}')

print('\n############################\n')

#Ex5
a = [1 , 2]
b = [1 , 4 , 5]
c = []
for i in a:
  for j in b:
    if i != j:
      c.append((i , j))
print(c)

print('\n############################\n')

#Ex 
a = [4.5 , float('nan') , 2.2 , 1.4]
b = []
for i in a:
  if not math.isnan(i):
    b.append(i)
print(a)
print(b)

# ----matrix----

a = [
    [1 , 2 , 3],
    [4 , 5 , 6],
    [7 , 8 , 9] 
     ]
print(a)
print(f'length = {len(a)}')
print(a[0])
print(a[2])

print()

for i in a:
  print(i)

for i in range(3):
  print(a[i][i] , end = ' ')

print()

for i in range(3):
  print(a[1][i] , end = ' ')

print()

for i in range(3):
  print(a[i][2-i] , end = ' ')

print()

print('\n############################\n')

b = []
b.extend([sum(i) for i in a])
print(b , end = ' ')

print()

c = []
for col in range(3):
    c.append(sum(i[col] for i in a))
print(c , end = ' ')    
print()

print('\n############################\n')

x = 2
y = x
y += 1
print(x)   # 2
print(y)   # 3

x = []
y = x
y.append(5)
print(x)    # [5]
print(y)    # [5]