# -*- coding: utf-8 -*-
"""project006.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNzXtyzBPyAY96bVbJZq0_QOiLga67CL

# **String :)**
"""

s = 'abcdef'
print(s[3])       #d
print(s[1 : 4])   #bcd
print(s[1 : -1])  #bcde
print(s[ : 4])    #abcd 
print(s[2 : ])    #cdef
print(s[ :: -1])   #fedcba

s = 'amirgholami'
print(len(s))
print(max(s))
print(min(s))
print(ord('a'))
print(chr(65))

print('\n====================\n')

s = 'amirrezamehrabani'
print(s.islower())
print(s.isupper())
print('a' in s)
print('o' not in s)
print(s.isalpha())
print(s.isalnum())
print(s.isdigit())

print('\n====================\n')

s = 'amirreza82'
print(s.isalnum())
print(s.isalpha())
print(s.isdigit())

print('\n====================\n')

s = '123456789'
print(s.isalnum())
print(s.isalpha())
print(s.isdigit())

print('\n====================\n')

s = '\t'
print(s.isspace())

#example
s = '1a2bc3def4'
k = 0
for ch in s:
  if ch.isdigit() == True:
    k += int(ch)

print('k = %i' %k)

s = 'amirreza mehrabani'
print(s.startswith('a'))
print(s.startswith('e'))
print(s.endswith('i'))
print(s.endswith('f'))

print('\n====================\n')

#find
print(s.find('a'))
print(s.find('a' , 0))
print(s.find('a' , 1))
print(s.find('a' , 8))
print(s.find('a' , 14))
print(s.find('g'))

print('\n====================\n')

#index
print(s.index('a'))
print(s.index('a' , 1))
print(s.index('a' , 8))   #print(s.index('g'))  ERROR

print('\n====================\n')

#count
#print(s.count())  ERROR
print(s.count('a'))
print(s.count('a' , 5))

print('\n====================\n')

#Example
s = 'amirreza82mh@gmail.com'
a = s.find('@')
print(s[a+1 : ])
print(len(s[a+1 : ]))

s = 'amirreza mehrabani'
print(s.capitalize())
print(s.title())
print(s.upper())

print('\n====================\n')

s = 'Amirreza MEhrabani'
print(s.lower())
print(s.swapcase())

print('\n====================\n')

s = 'amirreza mehrabani'
print(s.replace('mehrabani' , 'gholami'))
print(s)
print(s.replace('coft' , 'pedaret'))

from posixpath import split
#strip
s = '@@@AM@IR@'
print(s.strip('@'))
print(s.strip('A'))
print(s.lstrip('@'))
print(s.rstrip('@'))

print('\n====================\n')

s = '@@ali@@'
print(s.strip('@'))

print('\n====================\n')

#split
s = 'amir bia saresho begir'
a = s.split(' ')
print(a)
#join   s = ' '.join(b)
b = ['amir' , 'bia' , 'saresho' , 'begir']
s = " ".join(b)
print(s)
print('\n====================\n')

#Example
s = 'amirreza.py'
b = s.split('.')
print(b)
print(b[1])

print('\n====================\n')

#Example
s = 'amirreza@gmail.com'
u , d = s.split('@')
print(u)
print(d)

print('\n====================\n')

#Example 
s = 'amirreza\nmehrabani'
b = s.split('\n')
print(b)
b = s.splitlines()
print(b)

print('\n====================\n')

#example
s = '127.02.0.001'  #127.2.0.1
print(s)
a = s.split('.')
print(a)
k = '.'.join([str(int(i)) for i in a])
print(k)

s = '4242'
print(s.zfill(12))
print(s.ljust(9 , '+'))
print(s.rjust(9 , '+'))
print(s.center(9 , '+'))

print('\n====================\n')

s = 'sara'
print(s.zfill(7))
print(s.ljust(7 , '*'))
print(s.rjust(7 , '*'))
print(s.center(7 , '*'))

print('\n====================\n')

n = 14
print('{:d}'.format(n))   # 14
print('{0:d}'.format(n))  # 14
print('{:5d}'.format(n))   #   14

print('\n====================\n')

a = 12
b = 15
print('{0:d} , {1:.2f}'.format(a , b))
print('{1:d} , {0:.2f}'.format(a , b))
print('{0:.2f} , {1:d}'.format(a , b))
print('-----------------------------')
print(f'{a:d} , {b:.2f}')
print(f'{b:d} , {a:.2f}')
print(f'{a:.2f} , {b:d}')

print('\n====================\n')

a = 23421
print('{:,}'.format(a))
print(f'{a:,}')

print('\n====================\n')

a = 15.99
b = -15.99
print('{:.2f}'.format(a))
print('{:.2f}'.format(b))

print('\n====================\n')

a = 0.83
print('{0:.2%}'.format(a))
print(f'{a:.2%}')

print('\n====================\n')

d = 24
print('hexadecimal : ')
print('{0:X}'.format(d))
print('{0:#X}'.format(d))
print('-----------------------------')
print('binary : ')
print('{0:b}'.format(d))
print('{0:#b}'.format(d))