# -*- coding: utf-8 -*-
"""project003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5HLjb8iom6dJkkgsnWGQ44Uxo_ezKkq

# **Math Method.**
"""

#whith out importing math
print(abs(-5))
print(abs.__doc__)      
print(pow(4 , 3))    # 4*4*4
print(divmod(15,3))  # (15/3 , 15%3)
print(round(5.3))    # 5
print(round(5.6))    # 6

#whith importing math
import math
print(math.sqrt(4))
print(math.log10(100))
print(math.log(100))
print(math.log(math.e))
print(math.floor(6.7))
print(math.ceil(6.1))
print(math.fmod(34 , 4))
print(math.fmod(15 , 3))
print(math.pow(4 , 3))
print(math.trunc(3.9999))
print(math.factorial(3))
print(math.pi)
print(f'{math.pi :.2f}')

#random method
import random

print(random.randint(1 , 5))
print(random.choice([1 , 5]))
a = [1 , 3 , 5 , 7]
print(random.choice(a))
print(random.shuffle(a))
print(a)
print(random.shuffle(a))
print(a)
print(random.shuffle(a))
print(a)

#date time
import datetime
now = datetime.datetime.now()
print(now)
print(now.year)
print(now.day)
print(now.month)

#sys and os and platform
import sys 
import os
import platform

print(sys.version)
print(sys.platform)
print(platform.release)
print(os.getcwd)