# -*- coding: utf-8 -*-
"""[project008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_2pS8u57H4LPJquNV2jsT46wL_8Xwq-V

# tuple
"""

t = (2 , 4 , 5)
print(f'type = {type(t)}')
print(f'length = {len(t)}')

print('\n#####################\n')

#slice

t = (2 , 4 , 6 , 8 , 10 , 1 , 3)
print(t[0])
print(t[:4])
print(t[3 : 6])
print(t[4 :])
print(t[::-1])
print(t[ : 5 : 2])

print('\n#####################\n')

#index
t = ('amir' , 'gholam' , 'reza')
a = t.index('amir')
print(f'index of amir : {a}')
print('amir' in t)
print('gholam' not in t)

print('\n#####################\n')

#####
a = (3)
print(f'type of a : {type(a)}')
t = (3,)
print(f'type of t : {type(t)}')

print('\n#####################\n')

#max , min , sum , count
t = (1 , 2 , 3 , 4 , 5 , 6 , 1 , 1 , 1 , 2 , 2 , 2)
print(f'length a t : {len(t)}')
print(f'sum of tuple argumant : {sum(t)}')
print(f'max = {max(t)}')
print(f'min = {min(t)}')
print(f'number of 1 : {t.count(1)}')

print('\n#####################\n')

#concat and reverse
t = (1 , 2 , 3)
a = t * 2
print(a)

b = tuple(reversed(t))
print(f'revrese : {b}')

print('\n#####################\n')

#Comparison of tuples
a = (1 , 2)
b = (2 , 1)
c = (1 , 2)

print(f'comparison of a and b : {a == b}')
print(f'comparison of a and c : {a == c}')

#append?
t = (1 , 2 , 3 , 4)
a = (5,)
t = t + a               ## t.append(a)   ERROR
print(t)
#or
t1 = (1 , 2 , 3 , 4)
a = list(t1)
a.append(5)
t1 = tuple(a)
print(t)
t2 = (6 , 7)
b = list(t2)
a.append(b)
print(a)
t2 = tuple(a)
print(t2)

print('\n#####################\n')

#remove
t = (1 , 2 , 3 , 4 , 5)
a = list(t)
a.remove(2)
t = tuple(a)
print(t)

print('\n#####################\n')

#unpack
t = (12 , 24)
a, b = t
print(f'a = {a}')
print(f'b = {b}')

t = ('blue' , 10 , 'siapa')
color , year , brand = t
print(f'color = {color}')
print(f'year = {year}')
print(f'brand = {brand}')

print('\n#####################\n')

#zip
t1 = (1 , 2)
t2 = (3 , 4)
z = list(zip(t1 , t2))
print(f'ziped tuples : {z}')

t1 = (1 , 2)
t2 = (3 , 4)
t3 = (5 , 6)
z = list(zip(t1 , t2 , t3))
print(f'ziped tuple : {z}')

print('\n#####################\n')

#unzip
z = [(1 , 2 , 3) , (4 , 5 , 6)]
print(z)
u = list(zip(*z))
print(f'unziped tuples : {u}')

#Ex1
l = [(1 , 2) , 4 , 5 , (6,) , 7]
c = 0
for i in l:
  if isinstance(i , tuple):
    c += 1
print(f'the number of tuples : {c}')
print(len(l) - c)

print('\n#####################\n')

#Ex2         ###############################
a = [(1 , 2 , 3) , (4 , 5 , 6)]
b = [i[:2]+(9,) for i in a]
print(b)